### ISSUE TITLE
【Help】项目了解

### ISSUE THREAD

**Issue by xyy94813** [LiuJi-Jim/amap-react#1]
此项目是否是 AMap 官方提供？
该项目开源协议？

**Comment by LiuJi-Jim** [comment]
### 是否官方？

> 目前不是 100% 官方性质，意味着

* 你无法通过高德开放平台官网来提问或者反馈来获得技术支持
* 但如果你确实提了工单，那么内部应该还是能转到我这里来回复的
* 我正在努力将它完全官方化，当然这个过程中自然也离不开你们的多多使用与反馈

### 是否开源？

> 目前没有开源

* 首先这需要建立在把它“扶正”成为高德开放平台的官方项目的基础之上
* 其次还需要经过一系列略微有一丢丢复杂的内部流程
