### ISSUE TITLE
这个项目现在什么状态了，有开源计划么

### ISSUE THREAD

**Issue by DBvc** [LiuJi-Jim/amap-react#3]

**Comment by linsmalldragon** [comment]
不开源吗?

**Comment by LiuJi-Jim** [comment]
本人已经从高德离职，项目交由高德开放平台的同事维护了，如果需要技术支持，可以到[高德开放平台](https://lbs.amap.com/)提交工单，谢谢~

**Comment by linsmalldragon** [comment]
恭喜兄弟高就,如果有可能,也可以重新弄新建一个个人的amap开源. 找了半天github, 像 https://github.com/ElemeFE/react-amap 与 https://github.com/uiwjs/react-amap 这个, 写得乱还不受控. 这个算写得非常好的.就是看不见代码..
