### ISSUE TITLE
amap onclick 点击的时候拿不到经纬度？

### ISSUE THREAD

**Issue by Hemomoo** [LiuJi-Jim/amap-react#6]

**Comment by LiuJi-Jim** [comment]
Hi, 本人已经从高德离职，项目交由[高德开放平台](https://lbs.amap.com/)的同事维护了，如果需要技术支持，可以到高德开放平台提交工单，谢谢~

**Comment by jinmmd** [comment]
高德官方好像没有继续维护了？在官网上没有看到介绍，有些有始无终。。
