### ISSUE TITLE
新申请的js api key必需配合jscode，能在 config 中支持下 securityJsCode 属性吗？

### ISSUE THREAD

**Issue by jinmmd** [LiuJi-Jim/amap-react#7]
新申请的js api key必需配合jscode，能在 config 中支持下 securityJsCode 属性吗？

相关文档如下
https://lbs.amap.com/api/javascript-api/guide/abc/prepare

**Comment by LiuJi-Jim** [comment]
Hi, 本人已经从高德离职，项目交由[高德开放平台](https://lbs.amap.com/)的同事维护了，如果需要技术支持，可以到高德开放平台提交工单，谢谢~
